# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

	lane :beta do
		increment_version_number(
  bump_type: "minor", # Automatically increment minor version number
  xcodeproj: "clock888.xcodeproj"
)

		get_certificates           # invokes cert

  		get_provisioning_profile   # invokes sigh

  		build_app(scheme: "8:88",
            		workspace: "clock888.xcworkspace",
            		include_bitcode: true)

		upload_to_testflight
	end
end
